<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT scripts/generate_enums.php
 * ==========================================
 * 
 * MEASUREMENT_UNIT Enum 
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enum;

class MEASUREMENT_UNIT {

	const FL_OZ = 'fl oz';
	const OZ = 'oz';
	const SQ_FT = 'sq ft';
	const LBS = 'lbs';
	const COUNT = 'count';
	const LITER = 'L';
	const QUART = 'qt';
	const PINT = 'pt';
	const GALLON = 'gal';
	const PACK = 'pack';

}