<?php
/**
 * ==========================================
 * AUTOGENERATED FROM POSTGRESQL DATA
 * DO NOT EDIT DIRECTLY!!!
 * TO MODIFY, EDIT scripts/generate_enums.php
 * ==========================================
 * 
 * ORDER_STATUS Enum 
 *
 * @author      A Computer
 * @copyright   (c) 2015 G2G Market, Inc
 ********************************** 80 Columns *********************************
 */

namespace Pikd\Enum;

class ORDER_STATUS {

	const BASKET = 'Basket';
	const SHOPPING_LIST = 'Shopping List';
	const PENDING_PICKUP = 'Pending Pickup';
	const COMPLETE = 'Complete';
	const CANCELLED = 'Cancelled';

}